# https://taskfile.dev
version: '3'

vars:
  SNYK_SEVERITY: high

tasks:
  clean:
    cmds:
      - mvn clean

  package:
    deps: [clean]
    cmds:
      - mvn package

  package.uber-jar:
    deps: [clean]
    cmds:
      - mvn package assembly:single -DskipTests

  package.native-executable:
    deps: [clean]
    cmds:
      - mvn package native:compile-no-fork -DskipTests

  tag-version:
    cmds:
      - mvn versions:set -DnewVersion={{.CLI_ARGS}}
      - git commit -am "Set version to {{.CLI_ARGS}}"
      - git tag v{{.CLI_ARGS}}
      - git tag -l --sort=creatordate   --format='%(refname:short) -> %(creatordate)'

  snyk.test:
    cmds:
      - snyk test . --severity-threshold={{.SNYK_SEVERITY}}  --all-projects
      - snyk code test . --severity-threshold={{.SNYK_SEVERITY}} --all-projects
